plugins {
    id "com.android.application"
}

android {
    namespace = "com.mohave.browser"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.mohave.browser"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "0.1"
        ndk {
            abiFilters.add("arm64-v8a")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "org.mozilla.geckoview:geckoview:155.0.20260903215306"
}
